def convArticleHero(hero):
    if hero=="Lolita":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/lolita"
    elif hero=="Phoveus":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/phoveus"
    elif hero=="Uranus":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/uranus"
    elif hero=="Aulus":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/aulus"
    elif hero=="Cecilion":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/cecilion"
    elif hero=="Yve":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/yve"
    elif hero=="Valentina":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/valentina"
    elif hero=="Clint":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/clint"
    elif hero=="Diggie":
        return "https://shanbenzzz.com/mobile-legends/hero/support/diggie"
    elif hero=="Aldous":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/aldous"
    elif hero=="Esmeralda":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/esmeralda"
    elif hero=="Kimmy":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/kimmy"
    elif hero=="Gloo":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/gloo"
    elif hero=="Popol and Kupa":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/popol"
    elif hero=="Popol":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/popol"
    elif hero=="Lylia":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/lylia"
    elif hero=="Mathilda":
        return "https://shanbenzzz.com/mobile-legends/hero/support/mathilda"
    elif hero=="Freya":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/freya"
    elif hero=="Masha":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/masha"
    elif hero=="Irithel":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/irithel"
    elif hero=="Johnson":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/jhonson"
    elif hero=="Kaja":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/kaja"
    elif hero=="Lancelot":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/lancelot"
    elif hero=="Sun":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/sun"
    elif hero=="Khufra":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/khufra"
    elif hero=="Carmilla":
        return "https://shanbenzzz.com/mobile-legends/hero/support/carmilla"
    elif hero=="Yi Sun-shin":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/yi-sun-shin"
    elif hero=="Bane":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/bane"
    elif hero=="Argus":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/argus"
    elif hero=="Miya":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/miya"
    elif hero=="Claude":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/claude"
    elif hero=="Fanny":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/fanny"
    elif hero=="Moskov":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/moskov"
    elif hero=="Rafaela":
        return "https://shanbenzzz.com/mobile-legends/hero/support/rafaela"
    elif hero=="Kadita":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/kadita"
    elif hero=="Khaleed":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/khaleed"
    elif hero=="Helcurt":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/helcurt"
    elif hero=="Hylos":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/hylos"
    elif hero=="Yu Zhong":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/yu-zhong"
    elif hero=="Alice":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/alice"
    elif hero=="Odette":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/odette"
    elif hero=="Beatrix":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/beatrix"
    elif hero=="Ruby":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/ruby"
    elif hero=="Cyclops":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/cyclops"
    elif hero=="Kagura":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/kagura"
    elif hero=="Vale":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/vale"
    elif hero=="Bruno":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/bruno"
    elif hero=="Wanwan":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/wanwan"
    elif hero=="Gusion":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/gusion"
    elif hero=="Barats":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/barats"
    elif hero=="Lunox":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/lunox"
    elif hero=="Roger":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/roger"
    elif hero=="Eudora":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/eudora"
    elif hero=="Luo Yi":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/luo-yi"
    elif hero=="Floryn":
        return "https://shanbenzzz.com/mobile-legends/hero/support/floryn"
    elif hero=="Granger":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/granger"
    elif hero=="Baxia":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/baxia"
    elif hero=="Hanzo":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/hanzo"
    elif hero=="Yin":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/yin"
    elif hero=="Selena":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/selena"
    elif hero=="Zilong":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/zilong"
    elif hero=="Aurora":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/aurora"
    elif hero=="Chang'e":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/change"
    elif hero=="Franco":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/franco"
    elif hero=="Brody":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/brody"
    elif hero=="Natalia":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/natalia"
    elif hero=="Hayabusa":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/hayabusa"
    elif hero=="Atlas":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/atlas"
    elif hero=="Ling":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/ling"
    elif hero=="Pharsa":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/pharsa"
    elif hero=="Dyrroth":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/dyrus"
    elif hero=="Belerick":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/belerick"
    elif hero=="Minotaur":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/minotaur"
    elif hero=="Silvanna":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/silvanna"
    elif hero=="Melissa":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/melissa"
    elif hero=="Jawhead":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/jawhead"
    elif hero=="Akai":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/akai"
    elif hero=="Edith":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/edith"
    elif hero=="Angela":
        return "https://shanbenzzz.com/mobile-legends/hero/support/angela"
    elif hero=="Karina":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/karina"
    elif hero=="Benedetta":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/benedetta"
    elif hero=="Faramis":
        return "https://shanbenzzz.com/mobile-legends/hero/support/faramis"
    elif hero=="Paquito":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/paquito"
    elif hero=="Lapu-Lapu":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/lapu-lapu"
    elif hero=="Alucard":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/alucard"
    elif hero=="Estes":
        return "https://shanbenzzz.com/mobile-legends/hero/support/estes"
    elif hero=="Hanabi":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/hanabi"
    elif hero=="Saber":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/saber"
    elif hero=="Badang":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/badang"
    elif hero=="Gatotkaca":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/gatotkaca"
    elif hero=="X.Borg":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/x-borg"
    elif hero=="Natan":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/natan"
    elif hero=="Chou":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/chou"
    elif hero=="Leomord":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/leomord"
    elif hero=="Grock":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/grock"
    elif hero=="Lesley":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/lesly"
    elif hero=="Harley":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/harley"
    elif hero=="Balmond":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/balmond"
    elif hero=="Valir":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/valir"
    elif hero=="Hilda":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/hilda"
    elif hero=="Alpha":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/alpha"
    elif hero=="Guinevere":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/guinevere"
    elif hero=="Zhask":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/zhask"
    elif hero=="Aamon":
        return "https://shanbenzzz.com/mobile-legends/hero/assassin/aamon"
    elif hero=="Minsitthar":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/minsitthar"
    elif hero=="Gord":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/gord"
    elif hero=="Nana":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/nana"
    elif hero=="Karrie":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/karrie"
    elif hero=="Thamuz":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/thamuz"
    elif hero=="Tigreal":
        return "https://shanbenzzz.com/mobile-legends/hero/tank/tigreal"
    elif hero=="Martis":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/martis"
    elif hero=="Harith":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/harith"
    elif hero=="Layla":
        return "https://shanbenzzz.com/mobile-legends/hero/hunter/layla"
    elif hero=="Terizla":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/terizla"
    elif hero=="Vexana":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/vexana"
    elif hero=="Xavier":
        return "https://shanbenzzz.com/mobile-legends/hero/mage/xavier"
    elif hero=="Julian":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/julian"
    elif hero=="Fredrinn":
        return "https://shanbenzzz.com/mobile-legends/hero/fighter/fredrinn"
    elif hero=="Joy":
        return ""
    elif hero=="Arlott":
        return ""
    elif hero=="Novaria":
        return ""
    else :
        return "ヒーローなし"
