def convJaHeroName(hero):
    if hero=="Lolita":
        return "ロイン"
    elif hero=="Phoveus":
        return "フォヴィウス"
    elif hero=="Uranus":
        return "ウラノス"
    elif hero=="Aulus":
        return "アウルス"
    elif hero=="Cecilion":
        return "セシリオン"
    elif hero=="Yve":
        return "イヴ"
    elif hero=="Valentina":
        return "バレンティナ"
    elif hero=="Clint":
        return "クリント"
    elif hero=="Diggie":
        return "ディガー"
    elif hero=="Aldous":
        return "アウラド"
    elif hero=="Esmeralda":
        return "エスメラルダ"
    elif hero=="Kimmy":
        return "ジミー"
    elif hero=="Gloo":
        return "グルー"
    elif hero=="Popol and Kupa":
        return "ボボル&クバ"
    elif hero=="Popol":
        return "ボボル&クバ"
    elif hero=="Lylia":
        return "リリア"
    elif hero=="Mathilda":
        return "マチルダ"
    elif hero=="Freya":
        return "フレイヤ"
    elif hero=="Masha":
        return "マーシャ"
    elif hero=="Irithel":
        return "エレシル"
    elif hero=="Johnson":
        return "ジェイソン"
    elif hero=="Kaja":
        return "カチャ"
    elif hero=="Lancelot":
        return "ランスロット"
    elif hero=="Sun":
        return "悟空"
    elif hero=="Khufra":
        return "クッフラー"
    elif hero=="Carmilla":
        return "カーミラ"
    elif hero=="Yi Sun-shin":
        return "イスンシン"
    elif hero=="Bane":
        return "ベイン"
    elif hero=="Argus":
        return "アルゴス"
    elif hero=="Miya":
        return "マイヤ"
    elif hero=="Claude":
        return "クラウド"
    elif hero=="Fanny":
        return "ファニー"
    elif hero=="Moskov":
        return "モスコブ"
    elif hero=="Rafaela":
        return "ラファエル"
    elif hero=="Kadita":
        return "カティタ"
    elif hero=="Khaleed":
        return "カレード"
    elif hero=="Helcurt":
        return "ハカート"
    elif hero=="Hylos":
        return "ヘラクレス"
    elif hero=="Yu Zhong":
        return "ゾン"
    elif hero=="Alice":
        return "アリス"
    elif hero=="Odette":
        return "オデット"
    elif hero=="Beatrix":
        return "ビアトリクス"
    elif hero=="Ruby":
        return "ルビー"
    elif hero=="Cyclops":
        return "サイクロプス"
    elif hero=="Kagura":
        return "カグラ"
    elif hero=="Vale":
        return "ヴェル"
    elif hero=="Bruno":
        return "ブルーノ"
    elif hero=="Wanwan":
        return "琥珀"
    elif hero=="Gusion":
        return "ゴセン"
    elif hero=="Barats":
        return "バラッツ"
    elif hero=="Lunox":
        return "星夢"
    elif hero=="Roger":
        return "ロジャー"
    elif hero=="Eudora":
        return "エウドラ"
    elif hero=="Luo Yi":
        return "ローイ"
    elif hero=="Floryn":
        return "フローラ"
    elif hero=="Granger":
        return "グレンジャー"
    elif hero=="Baxia":
        return "玄覇"
    elif hero=="Hanzo":
        return "半蔵"
    elif hero=="Yin":
        return "寅"
    elif hero=="Selena":
        return "セリナ"
    elif hero=="Zilong":
        return "子龍"
    elif hero=="Aurora":
        return "オーロラ"
    elif hero=="Chang'e":
        return "嫦娥"
    elif hero=="Franco":
        return "フランコ"
    elif hero=="Brody":
        return "ブロディ"
    elif hero=="Natalia":
        return "ナタリア"
    elif hero=="Hayabusa":
        return "隼"
    elif hero=="Atlas":
        return "アテラス"
    elif hero=="Ling":
        return "リン"
    elif hero=="Pharsa":
        return "ファーサ"
    elif hero=="Dyrroth":
        return "ディアス"
    elif hero=="Belerick":
        return "カーディアン"
    elif hero=="Minotaur":
        return "ミノタウロス"
    elif hero=="Silvanna":
        return "シルバンナ"
    elif hero=="Melissa":
        return "メリッサ"
    elif hero=="Jawhead":
        return "メタルヘッド"
    elif hero=="Akai":
        return "ガイ"
    elif hero=="Edith":
        return "イーディス"
    elif hero=="Angela":
        return "アンジェラ"
    elif hero=="Karina":
        return "カリナ"
    elif hero=="Benedetta":
        return "ベラ"
    elif hero=="Faramis":
        return "マファセス"
    elif hero=="Paquito":
        return "パキート"
    elif hero=="Lapu-Lapu":
        return "ラプラプ"
    elif hero=="Alucard":
        return "アルカード"
    elif hero=="Estes":
        return "エスタス"
    elif hero=="Hanabi":
        return "ハナビ"
    elif hero=="Saber":
        return "セイバー"
    elif hero=="Badang":
        return "バターン"
    elif hero=="Gatotkaca":
        return "ガトートカチャ"
    elif hero=="X.Borg":
        return "エックス"
    elif hero=="Natan":
        return "ニュート"
    elif hero=="Chou":
        return "シュウ"
    elif hero=="Leomord":
        return "ラインロック"
    elif hero=="Grock":
        return "ガレック"
    elif hero=="Lesley":
        return "ラズリー"
    elif hero=="Harley":
        return "ハーリー"
    elif hero=="Balmond":
        return "バルモンド"
    elif hero=="Valir":
        return "ヴェルス"
    elif hero=="Hilda":
        return "ヒルダ"
    elif hero=="Alpha":
        return "アルファ"
    elif hero=="Guinevere":
        return "グネヴィア"
    elif hero=="Zhask":
        return "ザスク"
    elif hero=="Aamon":
        return "アモン"
    elif hero=="Minsitthar":
        return "マイシータール"
    elif hero=="Gord":
        return "グールド"
    elif hero=="Nana":
        return "ナナ"
    elif hero=="Karrie":
        return "キャリー"
    elif hero=="Thamuz":
        return "デームス"
    elif hero=="Tigreal":
        return "ティグラル"
    elif hero=="Martis":
        return "マーティス"
    elif hero=="Harith":
        return "ハリス"
    elif hero=="Layla":
        return "ライラ"
    elif hero=="Terizla":
        return "ディスラー"
    elif hero=="Vexana":
        return "サナ"
    elif hero=="Xavier":
        return "ザビエル"
    elif hero=="Julian":
        return "ジュリアン"
    else :
        return "ヒーローなし"