def convertRoleHeroName(hero):
    if hero=="Lolita":
        return ["Roam"]
    elif hero=="Phoveus":
        return ["EXP"]
    elif hero=="Uranus":
        return ["EXP"]
    elif hero=="Aulus":
        return ["EXP"]
    elif hero=="Cecilion":
        return ["Mid"]
    elif hero=="Yve":
        return ["Mid"]
    elif hero=="Valentina":
        return ["Mid", "EXP"]
    elif hero=="Clint":
        return ["Gold"]
    elif hero=="Diggie":
        return ["Roam"]
    elif hero=="Aldous":
        return ["EXP"]
    elif hero=="Esmeralda":
        return ["EXP"]
    elif hero=="Kimmy":
        return ["Gold"]
    elif hero=="Gloo":
        return ["EXP"]
    elif hero=="Popol and Kupa":
        return ["Gold"]
    elif hero=="Popol":
        return ["Gold"]
    elif hero=="Lylia":
        return ["Mid"]
    elif hero=="Mathilda":
        return ["Roam"]
    elif hero=="Freya":
        return ["EXP"]
    elif hero=="Masha":
        return ["Jungle"]
    elif hero=="Irithel":
        return ["Gold"]
    elif hero=="Johnson":
        return ["Roam"]
    elif hero=="Kaja":
        return ["EXP", "Roam"]
    elif hero=="Lancelot":
        return ["Jungle"]
    elif hero=="Sun":
        return ["EXP"]
    elif hero=="Khufra":
        return ["Roam"]
    elif hero=="Carmilla":
        return ["Roam"]
    elif hero=="Yi Sun-shin":
        return ["Jungle"]
    elif hero=="Bane":
        return ["EXP"]
    elif hero=="Argus":
        return ["EXP"]
    elif hero=="Miya":
        return ["Gold"]
    elif hero=="Claude":
        return ["Gold"]
    elif hero=="Fanny":
        return ["Jungle"]
    elif hero=="Moskov":
        return ["Gold"]
    elif hero=="Rafaela":
        return ["Roam"]
    elif hero=="Kadita":
        return ["Mid"]
    elif hero=="Khaleed":
        return ["EXP"]
    elif hero=="Helcurt":
        return ["Jungle"]
    elif hero=="Hylos":
        return ["Roam"]
    elif hero=="Yu Zhong":
        return ["EXP"]
    elif hero=="Alice":
        return ["EXP"]
    elif hero=="Odette":
        return ["Mid"]
    elif hero=="Beatrix":
        return ["Gold"]
    elif hero=="Ruby":
        return ["EXP", "Roam"]
    elif hero=="Cyclops":
        return ["Mid"]
    elif hero=="Kagura":
        return ["Mid"]
    elif hero=="Vale":
        return ["Mid"]
    elif hero=="Bruno":
        return ["Gold"]
    elif hero=="Wanwan":
        return ["Gold"]
    elif hero=="Gusion":
        return ["Jungle"]
    elif hero=="Barats":
        return ["EXP"]
    elif hero=="Lunox":
        return ["Mid"]
    elif hero=="Roger":
        return ["Jungle"]
    elif hero=="Eudora":
        return ["Mid"]
    elif hero=="Luo Yi":
        return ["Mid"]
    elif hero=="Floryn":
        return ["Roam"]
    elif hero=="Granger":
        return ["Jungle"]
    elif hero=="Baxia":
        return ["Roam"]
    elif hero=="Hanzo":
        return ["Jungle"]
    elif hero=="Yin":
        return ["Jungle"]
    elif hero=="Selena":
        return ["Roam"]
    elif hero=="Zilong":
        return ["EXP"]
    elif hero=="Aurora":
        return ["Mid"]
    elif hero=="Chang'e":
        return ["Mid"]
    elif hero=="Franco":
        return ["Roam"]
    elif hero=="Brody":
        return ["Gold"]
    elif hero=="Natalia":
        return ["Roam"]
    elif hero=="Hayabusa":
        return ["Jungle"]
    elif hero=="Atlas":
        return ["Roam"]
    elif hero=="Ling":
        return ["Jungle"]
    elif hero=="Pharsa":
        return ["Mid"]
    elif hero=="Dyrroth":
        return ["EXP"]
    elif hero=="Belerick":
        return ["Roam"]
    elif hero=="Minotaur":
        return ["Roam"]
    elif hero=="Silvanna":
        return ["Roam"]
    elif hero=="Melissa":
        return ["Gold"]
    elif hero=="Jawhead":
        return ["Roam"]
    elif hero=="Akai":
        return ["Roam"]
    elif hero=="Edith":
        return ["Gold", "Roam"]
    elif hero=="Angela":
        return ["Roam"]
    elif hero=="Karina":
        return ["Jungle"]
    elif hero=="Benedetta":
        return ["EXP"]
    elif hero=="Faramis":
        return ["Mid"]
    elif hero=="Paquito":
        return ["EXP"]
    elif hero=="Lapu-Lapu":
        return ["EXP"]
    elif hero=="Alucard":
        return ["Jungle"]
    elif hero=="Estes":
        return ["Roam"]
    elif hero=="Hanabi":
        return ["Gold"]
    elif hero=="Saber":
        return ["Jungle"]
    elif hero=="Badang":
        return ["EXP"]
    elif hero=="Gatotkaca":
        return ["EXP"]
    elif hero=="X.Borg":
        return ["EXP"]
    elif hero=="Natan":
        return ["Jungle"]
    elif hero=="Chou":
        return ["EXP"]
    elif hero=="Leomord":
        return ["EXP"]
    elif hero=="Grock":
        return ["Roam", "EXP"]
    elif hero=="Lesley":
        return ["Gold"]
    elif hero=="Harley":
        return ["Jungle"]
    elif hero=="Balmond":
        return ["EXP"]
    elif hero=="Valir":
        return ["Mid"]
    elif hero=="Hilda":
        return ["EXP", "Roam"]
    elif hero=="Alpha":
        return ["EXP"]
    elif hero=="Guinevere":
        return ["EXP"]
    elif hero=="Zhask":
        return ["EXP"]
    elif hero=="Aamon":
        return ["Jungle"]
    elif hero=="Minsitthar":
        return ["Roam", "EXP"]
    elif hero=="Gord":
        return ["Mid"]
    elif hero=="Nana":
        return ["Mid"]
    elif hero=="Karrie":
        return ["Gold"]
    elif hero=="Thamuz":
        return ["EXP"]
    elif hero=="Tigreal":
        return ["Roam"]
    elif hero=="Martis":
        return ["EXP"]
    elif hero=="Harith":
        return ["Gold"]
    elif hero=="Layla":
        return ["Gold"]
    elif hero=="Terizla":
        return ["EXP"]
    elif hero=="Vexana":
        return ["Mid"]
    elif hero=="Xavier":
        return ["Mid"]
    elif hero=="Julian":
        return ["Jungle", "EXP"]
    elif hero=="Fredrinn":
        return ["Jungle", "EXP"]
    elif hero=="Joy":
        return ["Jungle", "Mid"]
    elif hero=="Arlott":
        return ["Jungle", "EXP"]
    elif hero=="Novaria":
        return ["Mid"]
    else :
        return "ヒーローなし"
